privacymessage: "Mcme store your data only for the services"
messageactive: true
showplayerage: true
# wait-time in hour
wait-time: 24
listonjoin: true
broadcastlist: true
# broadcastlistevery in minutes
broadcastlistevery: 180
particles: true