version: 2.2
name: ${project.artifactId}
main: ${project.groupId}.mybirthday.birthday
website: ${project.url}
description: Birthday for MCME!
commands:
 birthday:
    aliases: [bd,birthd,bday]
    description: To set your birthday in game
