version: ${project.version}
name: ${project.artifactId}
api-version: 1.16
main: ${project.groupId}.mybirthday.MyBirthday
website: ${project.url}
softdepend: [DiscordSRV]
author: Fraspace5
description: Birthday for MCME!
commands:
 birthday:
    aliases: [bd,birthd,bday]
    description: To set your birthday in game
permissions:
    mybirthday.*:
        description: Allows to use all the commands of this plugin
        default: op
        children:
            mybirthday.set: true
            mybirthday.delete: true
            mybirthday.particles: true
# Copyright (C) 2020 MCME Fraspace5